# Vector of Light Client bootstrap nodes, used to bootstrap the DHT (mandatory field).
bootstraps = ["/dns/bootnode.2.lightclient.goldberg.avail.tools/tcp/37000/p2p/12D3KooWRCgfvaLSnQfkwGehrhSNpY7i5RenWKL2ARst6ZqgdZZd"]
# Vector of Relay nodes, which are used for hole punching
#relays = ["/ip4/13.49.44.246/tcp/39111/12D3KooWBETtE42fN7DZ5QsGgi7qfrN3jeYdXmBPL4peVTDmgG9b"]
# WebSocket endpoint of a full node for subscribing to the latest header, etc (default: ws://127.0.0.1:9944).
#full_node_ws = ["ws://127.0.0.1:9944"]
full_node_ws = ["wss://rpc-goldberg.sandbox.avail.tools:443", "wss://goldberg-rpc.fra.avail.tools:443"]
# wss://avail-goldberg.public.blastapi.io
# wss://lc-rpc-goldberg.avail.tools:443/ws
# wss://rpc-goldberg.sandbox.avail.tools
